name: Deploy Frontend
on:
  push:
    paths-ignore: 
      - 'core/**'
    branches:
      - deploy
      - master
  pull_request:
    paths-ignore: 
      - 'core/**'
    branches:
      - deploy

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd frontend yarn
      - name: Build
        env:
          CI: false
        run: yarn build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
